# Generated by Django 6.0.3 on 2026-03-23 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='devices.topic')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
