# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_topicdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceData",
        ),
    ]
