# Generated by Django 6.0.3 on 2026-03-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_devicedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name': 'Device state', 'verbose_name_plural': 'Device states'},
        ),
        migrations.AlterModelOptions(
            name='topicdata',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Device data', 'verbose_name_plural': 'Device data'},
        ),
    ]
