# Generated by Django 6.0.3 on 2026-03-23 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('dashboard_type', models.CharField(choices=[('GRID_TIED_MAIN', 'Grid-Tied Main'), ('GRID_TIED_MANAGEMENT', 'Grid-Tied Management'), ('APARTMENT_MAIN', 'Apartment Main'), ('APARTMENT_FLOOR_WISE', 'Apartment Floor Wise'), ('INDUSTRY_MAIN', 'Industry Main'), ('INDUSTRY_ZONING', 'Industry Zoning'), ('INDUSTRY_BOARD', 'Industry Board'), ('INDUSTRY_MD_CEO', 'Industry MD/CEO'), ('INDUSTRY_OWNER', 'Industry Owner')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
