# Generated by Django 6.0.3 on 2026-03-23

import django.db.models.deletion
import uuid
from django.db import migrations, models


CLIENT_TYPES = {
    "GRID_TIED": "Grid-Tied",
    "APARTMENT": "Apartment",
    "INDUSTRY": "Industry",
}

SCOPES = {
    "MAIN": "Main Dashboard",
    "MANAGEMENT": "Management Dashboard",
    "FLOOR_WISE": "Floor-wise Dashboard",
    "ZONING": "Zoning Dashboard",
    "BOARD": "Board Dashboard",
    "MD_CEO": "MD / CEO Dashboard",
    "OWNER": "Owner Dashboard",
}

DASHBOARD_TYPE_MAPPING = {
    "GRID_TIED_MAIN": ("GRID_TIED", "MAIN"),
    "GRID_TIED_MANAGEMENT": ("GRID_TIED", "MANAGEMENT"),
    "APARTMENT_MAIN": ("APARTMENT", "MAIN"),
    "APARTMENT_FLOOR_WISE": ("APARTMENT", "FLOOR_WISE"),
    "INDUSTRY_MAIN": ("INDUSTRY", "MAIN"),
    "INDUSTRY_ZONING": ("INDUSTRY", "ZONING"),
    "INDUSTRY_BOARD": ("INDUSTRY", "BOARD"),
    "INDUSTRY_MD_CEO": ("INDUSTRY", "MD_CEO"),
    "INDUSTRY_OWNER": ("INDUSTRY", "OWNER"),
}


def populate_dashboard_taxonomy(apps, schema_editor):
    ClientType = apps.get_model("dashboards", "ClientType")
    DashboardScope = apps.get_model("dashboards", "DashboardScope")
    Dashboard = apps.get_model("dashboards", "Dashboard")

    client_types = {}
    for code, name in CLIENT_TYPES.items():
        client_type, _ = ClientType.objects.get_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )
        client_types[code] = client_type

    scopes = {}
    for code, name in SCOPES.items():
        scope, _ = DashboardScope.objects.get_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )
        scopes[code] = scope

    for dashboard in Dashboard.objects.all():
        client_type_code, scope_code = DASHBOARD_TYPE_MAPPING.get(dashboard.dashboard_type, ("GRID_TIED", "MAIN"))
        dashboard.client_type = client_types[client_type_code]
        dashboard.scope = scopes[scope_code]
        dashboard.save(update_fields=["client_type", "scope"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DashboardScope",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="dashboard",
            name="client_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to="dashboards.clienttype",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to="dashboards.dashboardscope",
            ),
        ),
        migrations.RunPython(populate_dashboard_taxonomy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dashboard",
            name="client_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to="dashboards.clienttype",
            ),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashboards",
                to="dashboards.dashboardscope",
            ),
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="dashboard_type",
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(fields=("client_type", "scope"), name="unique_dashboard_client_type_scope"),
        ),
    ]
