# Generated by Django 6.0.3 on 2026-03-23 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('clients', '0001_initial'),
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboardaccess',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdashboardaccess',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to='dashboards.dashboard'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='omclientaccess',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_om_users', to='clients.client'),
        ),
        migrations.AddField(
            model_name='omclientaccess',
            name='om_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermissionoverride',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_override', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='clientdashboardaccess',
            constraint=models.UniqueConstraint(fields=('client_user', 'dashboard'), name='unique_client_dashboard_access'),
        ),
        migrations.AddConstraint(
            model_name='clientprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_client_profile_user'),
        ),
        migrations.AddConstraint(
            model_name='omclientaccess',
            constraint=models.UniqueConstraint(fields=('om_user', 'client'), name='unique_om_client_access'),
        ),
    ]
