# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_add_dashboard_scope"),
        ("access_control", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientDashboardAccess",
        ),
    ]
