# Generated by Django 6.0.3 on 2026-03-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0004_remove_clientprofile_unique_client_profile_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientProfile",
            new_name="UserClientAccess",
        ),
        migrations.AlterField(
            model_name="userclientaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="userclientaccess",
            name="unique_client_profile_user_client",
        ),
        migrations.AddConstraint(
            model_name="userclientaccess",
            constraint=models.UniqueConstraint(fields=("user", "client"), name="unique_user_client_access"),
        ),
    ]
