# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0005_rename_clientprofile_to_userclientaccess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPermissionOverride",
        ),
    ]
