# Generated by Django 6.0.3 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


def infer_client_type(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    ClientType = apps.get_model("dashboards", "ClientType")

    fallback = ClientType.objects.get(code="GRID_TIED")
    keyword_map = {
        "industry": "INDUSTRY",
        "apartment": "APARTMENT",
        "grid": "GRID_TIED",
    }

    for client in Client.objects.all():
        haystack = f"{client.code} {client.name}".lower()
        matched_type = fallback
        for keyword, code in keyword_map.items():
            if keyword in haystack:
                matched_type = ClientType.objects.get(code=code)
                break
        client.client_type = matched_type
        client.save(update_fields=["client_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_normalize_dashboard_models"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="dashboards.clienttype",
            ),
        ),
        migrations.RunPython(infer_client_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="client",
            name="client_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="dashboards.clienttype",
            ),
        ),
    ]
