# Generated by Django 6.0.3 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


def infer_dashboard_scope(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    DashboardScope = apps.get_model("dashboards", "DashboardScope")
    ClientDashboardAccess = apps.get_model("access_control", "ClientDashboardAccess")

    fallback_scope = DashboardScope.objects.get(code="MAIN")

    for client in Client.objects.all():
        access = (
            ClientDashboardAccess.objects.filter(client_user__client_profile__client=client)
            .select_related("dashboard__scope")
            .first()
        )
        client.dashboard_scope = access.dashboard.scope if access else fallback_scope
        client.save(update_fields=["dashboard_scope"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_normalize_dashboard_models"),
        ("clients", "0002_add_client_type"),
        ("access_control", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="dashboard_scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="dashboards.dashboardscope",
            ),
        ),
        migrations.RunPython(infer_dashboard_scope, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="client",
            name="dashboard_scope",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="dashboards.dashboardscope",
            ),
        ),
    ]
