# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("ASSIGN", "Assign"),
                    ("THRESHOLD_UPDATE", "Threshold Update"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                ],
                max_length=30,
            ),
        ),
    ]
